[package]
name = "wonderland-creator"
version = "0.1.0"
edition = "2021"
rust-version = "1.90"
license = "MPL-2.0"

[lib]
name = "wonderland_creator"

[[bin]]
name = "creator"
path = "src/main.rs"

[[test]]
name = "workspace"
path = "../../tests/tools/workspace.rs"

[[test]]
name = "city"
path = "../../tests/tools/city.rs"

[dependencies]
sha2 = "0.10"
wonderland-legacy-formats = { path = "../../crates/legacy-formats" }

[[test]]
name = "resources"
path = "../../tests/tools/resources.rs"

[[test]]
name = "cli"
path = "../../tests/tools/cli.rs"
