//! Synthetic bytecode. Expected numbers are derived from the source opcode
//! bodies, not generated by the interpreter under test.
use std::sync::Arc;
use wonderland_audio_runtime::{hit::*,mixer::*,AudioError};
use wonderland_render_core::AssetKey;
fn setup(bytes:Vec<u8>) -> (HitThread,HitHost) {
    let limits=HitLimits::default();
    let program=Arc::new(HitProgram::new(bytes,&limits).unwrap());
    (HitThread::new(program,0,&limits).unwrap(),HitHost::new(Arc::new(HitCatalog::default()),limits,19,1).unwrap())
}
fn long(bytes:&mut Vec<u8>,reg:u8,value:i32){bytes.extend([5,reg]);bytes.extend(value.to_le_bytes());}
#[test]
fn all_97_registry_slots_and_source_stub_operand_arities_remain_distinct(){
    let census=opcode_census();assert_eq!(census.len(),97);
    for (status,want) in [(OpcodeStatus::LiteralNoOp,50),(OpcodeStatus::ConsumingStub,8),(OpcodeStatus::InertDuck,2),(OpcodeStatus::BrokenWait,1),(OpcodeStatus::Operative,36)] { assert_eq!(census.iter().filter(|x|x.status==status).count(),want); }
    for info in census.iter().filter(|i|matches!(i.status,OpcodeStatus::LiteralNoOp|OpcodeStatus::ConsumingStub|OpcodeStatus::InertDuck)) {
        let mut b=vec![info.opcode];b.extend(vec![0xff;info.operands.unwrap() as usize]);b.extend([4,0,7,8]);
        let(mut t,mut h)=setup(b);t.tick(&mut h).unwrap();assert_eq!(t.read_var(0,&h).unwrap(),7,"{}",info.name);
    }
}
#[test]
fn signed_immediates_wrapping_arithmetic_and_cmp_flags(){
    let mut bytes=vec![4,2,255];long(&mut bytes,0,i32::MAX);long(&mut bytes,1,1);bytes.extend([0x10,0,1,0x14,0,2,8]);
    let(mut t,mut h)=setup(bytes);assert_eq!(t.tick(&mut h).unwrap(),ThreadStep::ExecutionEnded);
    assert_eq!(t.read_var(2,&h).unwrap(),-1);assert_eq!(t.read_var(0,&h).unwrap(),i32::MIN);assert!(t.sign);assert!(!t.zero);
    let (mut t,mut h)=setup(vec![4,0,249,4,1,2,0x12,0,1,0x13,0,1,0x11,0,1,8]);t.tick(&mut h).unwrap();assert_eq!(t.read_var(0,&h).unwrap(),-8);
}
#[test]
fn division_faults_do_not_leave_a_live_thread(){
    for (a,b) in [(7,0),(i32::MIN,-1)] {let mut bytes=vec![];long(&mut bytes,0,a);long(&mut bytes,1,b);bytes.extend([0x12,0,1]);let(mut t,mut h)=setup(bytes);assert_eq!(t.tick(&mut h),Err(AudioError::Fault("division")));assert!(t.dead);}
}
#[test]
fn min_max_are_immediate_and_set_copies_flags(){
    let mut bytes=vec![4,0,247,4,1,6,6,2,0,0x4a,3,1,0x2d,0];bytes.extend((-4i32).to_le_bytes());bytes.extend([0x2e,1]);bytes.extend(2i32.to_le_bytes());bytes.push(8);
    let(mut t,mut h)=setup(bytes);t.tick(&mut h).unwrap();assert_eq!(t.read_var(0,&h).unwrap(),-4);assert_eq!(t.read_var(1,&h).unwrap(),2);assert_eq!(t.read_var(2,&h).unwrap(),-9);assert_eq!(t.read_var(3,&h).unwrap(),6);
}
#[test]
fn end_returns_to_call_but_return_kills_even_with_caller(){
    let(mut t,mut h)=setup(vec![7,9,0,0,0,4,0,7,8,4,0,3,0x0c]);t.tick(&mut h).unwrap();assert_eq!(t.read_var(0,&h).unwrap(),7);
    let(mut t,mut h)=setup(vec![7,9,0,0,0,4,0,7,8,4,0,3,8]);t.tick(&mut h).unwrap();assert_eq!(t.read_var(0,&h).unwrap(),3);
}
#[test]
fn wait_latches_and_subtracts_16_until_exact_boundary(){
    let(mut t,mut h)=setup(vec![4,0,32,9,0,4,1,77,8]);assert_eq!(t.tick(&mut h).unwrap(),ThreadStep::Halted);assert_eq!(t.pc,3);assert_eq!(t.wait_remain,16);
    t.write_var(0,100,&mut h).unwrap();assert_eq!(t.tick(&mut h).unwrap(),ThreadStep::ExecutionEnded);assert_eq!(t.read_var(1,&h).unwrap(),77);assert_eq!(t.wait_remain,-1);
}
#[test]
fn register_jump_inspects_target_and_skips_three_only_for_target_nop(){
    let(mut t,mut h)=setup(vec![4,0,5,0x0d,0,0,0x61,0x61,4,1,9,8]);t.tick(&mut h).unwrap();assert_eq!(t.read_var(1,&h).unwrap(),9);
    let(mut t,mut h)=setup(vec![4,0,5,0x0d,0,4,1,8,8]);t.tick(&mut h).unwrap();assert_eq!(t.read_var(1,&h).unwrap(),8);
    let mut b=vec![0x0d,16,0,0,0];b.resize(16,0x61);b.extend([4,1,42,8]);let(mut t,mut h)=setup(b);t.tick(&mut h).unwrap();assert_eq!(t.read_var(1,&h).unwrap(),42);
}
#[test]
fn each_conditional_branch_obeys_zero_and_sign_flags(){
    for (op,value,taken) in [(0x3e,0,true),(0x3e,1,false),(0x3f,1,true),(0x3f,0,false),(0x40,1,true),(0x40,-1,false),(0x41,-1,true),(0x41,0,false),(0x42,0,true),(0x42,-1,false),(0x43,0,true),(0x43,1,false)] {
        let(mut t,mut h)=setup(vec![4,0,value as u8,0x0e,0,op,14,0,0,0,4,1,44,8,4,1,55,8]);t.tick(&mut h).unwrap();assert_eq!(t.read_var(1,&h).unwrap(),if taken{55}else{44},"op {op}");
    }
}
#[test]
fn source_quirks_random_bounds_broken_wait_and_literal_global_store(){
    let(mut t,mut h)=setup(vec![4,2,99,4,3,1,0x18,0,2,2,0x4d,2,3,0x56,2,0,0,0,0,0x57,1,0,0,0,0,8]);t.tick(&mut h).unwrap();assert_eq!(t.read_var(0,&h).unwrap(),2);assert_eq!(t.read_var(1,&h).unwrap(),2);assert_eq!(h.globals[0],2);
}
#[test]
fn variable_gaps_and_patch_side_effects_match_source_but_bad_fields_fault(){
    let(mut t,mut h)=setup(vec![8]);assert_eq!(t.read_var(1,&h).unwrap(),12);
    for addr in [0x46,0x63,0x88,0x2719,0x2737] {t.write_var(addr,42,&mut h).unwrap();assert_eq!(t.read_var(addr,&h).unwrap(),0);}
    for addr in [0x12,0x32] {t.write_var(addr,55,&mut h).unwrap();assert_eq!(t.patch,Some(55));}
    t.write_var(0x64,9,&mut h).unwrap();assert_eq!(h.globals[0],9);
    t.objects=vec![7];assert_eq!(t.read_var(0x271a,&h).unwrap(),7);assert!(t.read_var(0x271b,&h).is_err());assert!(t.read_var(-1,&h).is_err());
}
#[test]
fn get_src_data_field_uses_current_owner_despite_source_operand(){
    let(mut t,mut h)=setup(vec![4,0,88,4,1,12,0x48,2,0,1,8]);t.objects[12]=77;t.tick(&mut h).unwrap();assert_eq!(t.read_var(2,&h).unwrap(),77);
}
#[test]
fn malformed_and_runaway_programs_are_bounded(){
    for bytes in [vec![5,0,1],vec![0x61],vec![7,255,255,255,255]] {let(mut t,mut h)=setup(bytes);assert!(t.tick(&mut h).is_err());assert!(t.dead);}
    let(mut t,mut h)=setup(vec![0x21,0x20]);h.limits.instructions_per_tick=20;assert_eq!(t.tick(&mut h),Err(AudioError::Limit("instructions per tick")));
    let(mut t,mut h)=setup(vec![7,0,0,0,0]);h.limits.call_depth=2;assert_eq!(t.tick(&mut h),Err(AudioError::Limit("call depth")));
    let(mut t,mut h)=setup(vec![0;32]);h.limits.instructions_per_tick=8;assert!(t.tick(&mut h).is_err());
}
#[test]
fn missing_note_loop_still_halts_and_wait_sample_completion_halts_once(){
    let(mut t,mut h)=setup(vec![0x60,0,4,1,6,0x0b,4,1,8,8]);assert_eq!(t.tick(&mut h).unwrap(),ThreadStep::Halted);assert_eq!(t.read_var(0,&h).unwrap(),-1);
    assert_eq!(t.tick(&mut h).unwrap(),ThreadStep::Halted);assert_eq!(t.read_var(1,&h).unwrap(),6);assert_eq!(t.tick(&mut h).unwrap(),ThreadStep::ExecutionEnded);assert_eq!(t.read_var(1,&h).unwrap(),8);
}
#[test]
fn queue_is_ordered_and_fault_cleanup_releases_each_owned_voice_once(){
    let limits=HitLimits::default();let mut cat=HitCatalog::default();cat.samples.insert(7,SampleRef{key:AssetKey([7;32]),group:VolumeGroup::Vox,sample_rate:60,frames:6});
    let mut h=HitHost::new(Arc::new(cat),limits.clone(),1,8).unwrap();let mut t=HitThread::new(Arc::new(HitProgram::new(vec![4,0x12,7,2,0,2,1,0x0b,8],&limits).unwrap()),0,&limits).unwrap();
    t.tick(&mut h).unwrap();assert_eq!(t.active_notes(),2);let intents=h.drain_intents();assert_eq!(intents.len(),2);
    let voices:Vec<_>=intents.iter().map(|i|if let MixerIntent::Start{voice,group,..}=i{assert_eq!(*group,VolumeGroup::Vox);*voice}else{panic!()}).collect();assert!(voices[0].serial<voices[1].serial);
    assert_eq!(t.pc,7);t.complete_voice(voices[1]);t.tick(&mut h).unwrap();assert_eq!(t.pc,8);t.tick(&mut h).unwrap();assert!(t.thread_dead);t.tick(&mut h).unwrap();assert!(t.dead);
    assert_eq!(h.drain_intents().iter().filter(|x|matches!(x,MixerIntent::Release{..})).count(),2);t.tick(&mut h).unwrap();assert!(h.drain_intents().is_empty());
}
#[test]
fn smart_index_can_replace_hitlist_and_returns_second_lookup(){
    let limits=HitLimits::default();let mut cat=HitCatalog::default();cat.hitlists.insert(1,vec![20]);cat.hitlists.insert(2,vec![99]);cat.tracks.insert(20,Track{track_id:20,sound_id:8,hitlist_id:Some(2),looped:Some(true)});
    let mut h=HitHost::new(Arc::new(cat),limits.clone(),1,1).unwrap();let mut t=HitThread::new(Arc::new(HitProgram::new(vec![4,0,1,0x44,0,4,0,0,0x5f,1,0,8],&limits).unwrap()),0,&limits).unwrap();t.tick(&mut h).unwrap();assert_eq!(t.read_var(1,&h).unwrap(),99);assert_eq!(t.patch,Some(8));assert!(t.looped);
}
